---
framework: jest
preRun:
     command:
        - npm ci
preMerge:
  pattern:
    - "./**/unit/**/*.spec.js"
    - "test/integration/*.spec.js"
postMerge:
  pattern: 
    - "./**/unit/**/*.spec.js"
    - "test/integration/*.spec.js"
version: 1.0
parallelism: 4
splitMode: file
